<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-festas_da_aldeia_pages-1b83a94f-754a-46f0-a93b-5aa7e9fc570e</UserSecretsId>
    <RootNamespace>festas_da_aldeia_pages</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\festas da aldeia\Data\ApplicationDbContext.cs" Link="Shared\Data\ApplicationDbContext.cs" />
    <Compile Include="..\festas da aldeia\Data\DbSeeder.cs" Link="Shared\Data\DbSeeder.cs" />
    <Compile Include="..\festas da aldeia\Models\Artista.cs" Link="Shared\Models\Artista.cs" />
    <Compile Include="..\festas da aldeia\Models\Cartaz.cs" Link="Shared\Models\Cartaz.cs" />
    <Compile Include="..\festas da aldeia\Models\Evento.cs" Link="Shared\Models\Evento.cs" />
    <Compile Include="..\festas da aldeia\Models\Local.cs" Link="Shared\Models\Local.cs" />
  </ItemGroup>

</Project>
